apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: app
  name: monitor-app
  namespace: aluno-jose
spec:
  podMetricsEndpoints:
  - port: "5000"
    interval: 10s
  selector:
    matchLabels:
      app: app
